# Generated by Django 5.2.3 on 2025-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
