# Generated by Django 5.2.3 on 2025-06-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0002_bookinglog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingLog',
            new_name='Booking_list',
        ),
    ]
